spring:
  application:
    name: hello-spring-cloud-zuul
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411


server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-ribbon:
      path: /api/ribbon/**
      serviceId: hello-spring-cloud-web-admin-ribbon
    api-feign:
      path: /api/feign/**
      serviceId: hello-spring-cloud-web-admin-feign
